#!/bin/bash

# Check if the flag was passed as an argument
if [ $# -eq 0 ]; then
  echo "Please provide a flag (0 for lexical analysis, 1 for syntactic and semantic analysis)."
  exit 1
fi

# The flag passed as an argument
flag=$1

# Check if the flag is valid (0 or 1)
if [ "$flag" -eq 0 ]; then
  java -cp ./bin compiler_modules.Compiler 0
elif [ "$flag" -eq 1 ]; then
  java -cp ./bin compiler_modules.Compiler 1
else
  echo "Invalid flag. Use 0 for lexical analysis or 1 for syntactic and semantic analysis."
  exit 1
fi
